# Generated by Django 5.2.1 on 2025-05-12 19:40

import books.models
import storage.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(max_length=500, storage=storage.supabase_storage.SupabaseStorage, upload_to='images/', validators=[books.models.imagevalidator]),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(max_length=500, storage=storage.supabase_storage.SupabaseStorage, upload_to='eBooks/', validators=[books.models.validate_pdf]),
        ),
    ]
