# Generated by Django 5.2.1 on 2025-05-11 21:09

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, validators=[books.models.validate_length]),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(max_length=500, storage=books.models.get_supabase_storage, upload_to='images/', validators=[books.models.imagevalidator]),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(max_length=500, storage=books.models.get_supabase_storage, upload_to='eBooks/', validators=[books.models.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, max_length=100, null=True, validators=[books.models.validate_length]),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[books.models.validate_length]),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=100, validators=[books.models.validate_length]),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, validators=[books.models.validate_length]),
        ),
    ]
