# Generated by Django 5.2.1 on 2025-05-09 22:55

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_author_alter_book_publisher_delete_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(upload_to='storage/covers/', validators=[books.models.imagevalidator]),
        ),
    ]
